/**
 * Autogenerated index of available build tasks, or "builder" objects.
 * @module pwa-devdocs/builders
 */
const { basename } = require('path');
const { readdirSync } = require('fs');

function tryResolve(entry) {
    try {
        return require.resolve('./' + entry);
    } catch (e) {
        return false;
    }
}

/**
 * Autogenerate the list of builders by reading the directory.
 *
 */
const builders = {};
const all = [];
for (const entry of readdirSync(__dirname)) {
    const builderModule = tryResolve(entry);
    if (builderModule && builderModule !== __filename) {
        const builderModuleName = basename(entry, '.js');
        builders[builderModuleName] = builderModule;
        all.push(builderModuleName);
    }
}

/**
 * Mapping of task name to module path.
 * Use to require a builder by name:
 *
 *     require(builders['ref-docs']);
 * @type {object}
 * @memberof pwa-devdocs/builders
 */
module.exports.builders = builders;

/**
 * Array of all task names.
 * Use to require all tasks:
 *
 *     all.map(name => require(builders[name]))
 * @type {string[]}
 * @memberof pwa-devdocs/builders
 */
module.exports.all = all;
